"""Create initial tables

Revision ID: ea02b24bdb44
Revises: 
Create Date: 2026-04-28 19:09:52.284694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea02b24bdb44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('agent_response', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('workflow_step', sa.Integer(), nullable=True),
    sa.Column('tool_calls', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('error_occurred', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_session_id'), 'agent_logs', ['session_id'], unique=False)
    op.create_table('loss_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('pattern_name', sa.String(), nullable=False),
    sa.Column('pattern_description', sa.Text(), nullable=False),
    sa.Column('intent_type', sa.String(), nullable=True),
    sa.Column('workflow_step', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('total_occurrences', sa.Integer(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('avg_quality_score', sa.Float(), nullable=True),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('root_cause_confidence', sa.Float(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('primary_intent', sa.String(), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('workflow_completed', sa.Boolean(), nullable=True),
    sa.Column('drop_off_step', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('success_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_log_id', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('helpfulness_score', sa.Float(), nullable=False),
    sa.Column('goal_alignment_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('evaluation_reasoning', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('evaluator_model', sa.String(), nullable=False),
    sa.Column('evaluation_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_log_id'], ['agent_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eval_results')
    op.drop_table('session_summaries')
    op.drop_table('loss_patterns')
    op.drop_index(op.f('ix_agent_logs_session_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
